<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button</name>
   <tag></tag>
   <elementGuidId>f2200a91-d176-4d59-8cb8-2f579934065d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.m-button--submit</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
